package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "common",
    deps = [
        "//adabrain/summarization/resolution/common/data",
        "//adabrain/summarization/resolution/common/metrics",
        "//adabrain/summarization/resolution/common/models",
        "//adabrain/summarization/resolution/common/modules",
        "//adabrain/summarization/resolution/common/predictors",
        "//adabrain/summarization/resolution/common/utils",
    ]
)