package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

py_library(
    name = "utils",
    srcs = glob([
        "*.py",
    ])
)